version: '3'
services:
  et:
    image: 'et_full_system:1.0.0.pre'
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        GEM_VERSION:

    ports:
      - '${SERVER_PORT:-3100}:${SERVER_PORT:-3100}'
      - '${TRAEFIX_PORT:-3200}:${TRAEFIK_PORT:-3200}'
      - '${SMTP_PORT:-1025}:${SMTP_PORT:-1025}'
    extra_hosts:
      - "localhost.from.docker:${LOCALHOST_FROM_DOCKER_IP}"
    volumes:
      - rvm:/usr/local/rvm
      - global_node_modules:/usr/lib/node_modules
      - ${PWD}:/home/app/full_system
      - et1_node_modules:/home/app/full_system/systems/et1/node_modules
      - et3_node_modules:/home/app/full_system/systems/et3/node_modules
      - api_node_modules:/home/app/full_system/systems/api/node_modules
      - admin_node_modules:/home/app/full_system/systems/admin/node_modules
      - et1_assets:/home/app/full_system/systems/et1/public/apply/assets
      - et3_assets:/home/app/full_system/systems/et3/public/assets
      - admin_assets:/home/app/full_system/systems/admin/public/assets
      - s3_data:/home/app/minio_data
      - azure_storage_data:/home/app/azure_storage_data
      - et1_bundle:/home/app/full_system/systems/et1/.bundle
      - et3_bundle:/home/app/full_system/systems/et3/.bundle
      - api_bundle:/home/app/full_system/systems/api/.bundle
      - atos_bundle:/home/app/full_system/systems/atos/.bundle
      - admin_bundle:/home/app/full_system/systems/admin/.bundle
      - admin_bundle:/home/app/full_system/systems/et_ccd_export/.bundle
      - ./.empty:/home/app/full_system/systems/et1/.env
      - ./.empty:/home/app/full_system/systems/et3/.env
      - ./.empty:/home/app/full_system/systems/api/.env
      - ./.empty:/home/app/full_system/systems/atos/.env
      - ./.empty:/home/app/full_system/systems/admin/.env
      - ./.empty:/home/app/full_system/systems/et_ccd_export/.env
      - ./.empty:/home/app/full_system/systems/et1/.env.local
      - ./.empty:/home/app/full_system/systems/et3/.env.local
      - ./.empty:/home/app/full_system/systems/api/.env.local
      - ./.empty:/home/app/full_system/systems/atos/.env.local
      - ./.empty:/home/app/full_system/systems/admin/.env.local
      - ./.empty:/home/app/full_system/systems/et_ccd_export/.env.local
    environment:
      DISABLE_CLOUDWATCH: 'true'
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      RAILS_ENV:
      RAILS_LOG_LEVEL:
      REDIS_HOST: redis
      SERVER_PORT: ${SERVER_PORT:-3100}
      SERVER_DOMAIN: ${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
      CLOUD_PROVIDER: ${CLOUD_PROVIDER:-amazon}
      AZURITE_STORAGE_PATH: /home/app/azure_storage_data
      MINIO_STORAGE_PATH: /home/app/minio_data
      SHOW_DOWNTIME_BANNER:
      CCD_AUTH_BASE_URL: ${CCD_AUTH_BASE_URL:-http://ccd.et.127.0.0.1.nip.io:3100/auth}
      CCD_IDAM_BASE_URL: ${CCD_IDAM_BASE_URL:-http://ccd.et.127.0.0.1.nip.io:3100/idam}
      CCD_DATA_STORE_BASE_URL: ${CCD_DATA_STORE_BASE_URL:-http://ccd.et.127.0.0.1.nip.io:3100/data_store}
      CCD_DOCUMENT_STORE_BASE_URL: ${CCD_DOCUMENT_STORE_BASE_URL:-http://ccd.et.127.0.0.1.nip.io:3100/document_store}
      CCD_DOCUMENT_STORE_URL_REWRITE: ${CCD_DOCUMENT_STORE_URL_REWRITE:-false}
      CCD_USE_SIDAM: ${CCD_USE_SIDAM:-true}
      CCD_MICROSERVICE_ID: ${CCD_MICROSERVICE_ID:-ccd_gw}
      CCD_MICROSERVICE_SECRET: ${CCD_MICROSERVICE_SECRET:-AAAAAAAAAAAAAAAC}
      CCD_SIDAM_USERNAME: ${CCD_SIDAM_USERNAME:-m@m.com}
      CCD_SIDAM_PASSWORD: ${CCD_SIDAM_PASSWORD:-p}
      CCD_GENERATE_ETHOS_CASE_REFERENCE: ${CCD_GENERATE_ETHOS_CASE_REFERENCE:-false}
      AZURE_APP_INSIGHTS_KEY: ${AZURE_APP_INSIGHTS_KEY:-2ac37587-9187-4ec1-97a4-d12ba26bc0fc}
    command: /bin/bash --login -c "cd /home/app/full_system && et_full_system local server --azurite-storage-path=/home/app/azure_storage_data --minio-storage-path=/home/app/minio_data ${SERVER_ARGS}"
    links:
      - "db"
      - "redis"
    networks:
      et_full_system:
        aliases:
          - api.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - admin.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - et1.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - et3.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - s3.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - azure_blob_storage.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - azure.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - atos.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - mail.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}
          - ccd.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}

#command: bash -lc "cd /home/app/full_system/systems/api && REDIS_DATABASE=2 bundle exec sidekiq"
  db:
    image: postgres:9.6.9
    networks:
      - et_full_system
    ports:
      - "${DB_PORT:-0}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-0}:6379"
    networks:
      - et_full_system
    volumes:
      - redis_data:/data
  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - et_full_system
    extra_hosts:
      - "localhost.from.docker:${LOCALHOST_FROM_DOCKER_IP}"
  chrome:
    image: selenium/node-chrome:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    extra_hosts:
      - "localhost.from.docker:${LOCALHOST_FROM_DOCKER_IP}"
    networks:
      - et_full_system
  firefox:
    image: selenium/node-firefox:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    extra_hosts:
      - "localhost.from.docker:${LOCALHOST_FROM_DOCKER_IP:-127.255.255.255}"
    networks:
      - et_full_system
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - zalenium_videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
    extra_hosts:
      - "localhost.from.docker:${LOCALHOST_FROM_DOCKER_IP}"
    networks:
      - et_full_system
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 1024 --screenHeight 768
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --lambdaTestEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
      - PULL_SELENIUM_IMAGE=true
volumes:
  rvm:
  global_node_modules:
  et1_node_modules:
  et3_node_modules:
  s3_node_modules:
  api_node_modules:
  admin_node_modules:
  et1_assets:
  et3_assets:
  admin_assets:
  s3_data:
  azure_storage_data:
  et1_bundle:
  et3_bundle:
  admin_bundle:
  api_bundle:
  atos_bundle:
  db_data:
  redis_data:
  zalenium_videos:

networks:
  et_full_system:


